# Generated by Django 4.2.7 on 2023-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('curso', models.CharField(max_length=100)),
                ('dataInicio', models.DateField()),
                ('presencas', models.IntegerField()),
                ('aulasRestantes', models.IntegerField()),
            ],
        ),
    ]
